
name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT_ID: purva-api
  SERVICE_NAME: backend-infra
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Setup Google Cloud
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        if: github.ref == 'refs/heads/master'
        run: gcloud auth configure-docker

      - name: Build and Push Container
        if: github.ref == 'refs/heads/master'
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Create env.yaml
        if: github.ref == 'refs/heads/master'
        run: |
          cat > env.yaml << EOF
          FIREBASE_PROJECT_ID: $PROJECT_ID
          GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
          EOF

      - name: Deploy to Cloud Run
        if: github.ref == 'refs/heads/master'
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --env-vars-file env.yaml \
